---
- name: wordpress環境構築 for web
  hosts: web
  gather_facts: no
  remote_user: jenkins
  become: yes

  vars:
    wordpress_url: http://wordpress.org/latest.tar.gz

  tasks:
  - name: Apache（httpd）のインストール
    yum: name=httpd state=latest

  - name: サービスの起動
    service: name=httpd state=started enabled=yes

  - name: PHPのインストール
    yum: name="{{item}}" state=latest
    with_items:
      - php
      - php-mysql
    notify: restart httpd


  - name: タイムゾーンの設定
    ini_file: >
      dest=/etc/php.ini
      section=Date
      option=date.timezone
      value='"Asia/Tokyo"'
  - name: wordpressのダウンロード
    get_url:
      url="{{wordpress_url}}"
      dest=/tmp/wordpress.tar.gz

  - name: wordpressの展開
    unarchive:
      src=/tmp/wordpress.tar.gz
      dest=/var/www/html
      copy=no
      creates=/var/www/html/wordpress

  - name: wordpressの所有権をapacheに変更
    file: path=/var/www/html/wordpress/ owner=apache group=apache recurse=yes

  - name: httpサービスの起動
    service: name=httpd state=restarted

  - name: NTPのインストール
    yum: name=ntp state=latest

  - name: NTPサービスの起動
    service: name=ntpd state=started enabled=yes

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
